"""adicionao a tabela banner e ligando a tabela 

Revision ID: 2852fb0d5d7f
Revises: d11a75eb026a
Create Date: 2025-06-16 01:35:08.477984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2852fb0d5d7f'
down_revision = 'd11a75eb026a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('nivel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nivel_id'], ['nivel.id'], ),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banners')
    # ### end Alembic commands ###
