"""Atualizando e criando tabela miniatura e controller

Revision ID: 2aef7f6d75f7
Revises: 694a6905fd0d
Create Date: 2025-06-22 12:26:48.333081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2aef7f6d75f7'
down_revision = '694a6905fd0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miniatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagem_id', sa.Integer(), nullable=False),
    sa.Column('dados_miniatura', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['imagem_id'], ['imagem.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imagem_id')
    )
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.alter_column('imagem_blob',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)

    with op.batch_alter_table('imagem', schema=None) as batch_op:
        batch_op.alter_column('dados_imagem',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagem', schema=None) as batch_op:
        batch_op.alter_column('dados_imagem',
               existing_type=sa.LargeBinary(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)

    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.alter_column('imagem_blob',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    op.drop_table('miniatura')
    # ### end Alembic commands ###
