"""Atualizando

Revision ID: 77a4c169092e
Revises: ba5a4f32e9fa
Create Date: 2025-06-16 23:40:45.855524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77a4c169092e'
down_revision = 'ba5a4f32e9fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.alter_column('imagem_blob',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)

    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produto_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'produtos', ['produto_id'], ['id'])
        batch_op.drop_column('produtos_ids')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produtos_ids', mysql.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('produto_id')

    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.alter_column('imagem_blob',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
