"""Atualizando e criando tabela cupom e o controller

Revision ID: 9ac7f0066639
Revises: 2aef7f6d75f7
Create Date: 2025-06-22 13:14:23.798532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ac7f0066639'
down_revision = '2aef7f6d75f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.alter_column('imagem_blob',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)

    with op.batch_alter_table('imagem', schema=None) as batch_op:
        batch_op.alter_column('dados_imagem',
               existing_type=sa.BLOB(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagem', schema=None) as batch_op:
        batch_op.alter_column('dados_imagem',
               existing_type=mysql.LONGBLOB(),
               type_=sa.BLOB(),
               existing_nullable=False)

    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.alter_column('imagem_blob',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
