"""adicionao a tabela banner e ligando a tabela 

Revision ID: ba5a4f32e9fa
Revises: c48ba4da9e02
Create Date: 2025-06-16 23:35:10.073011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba5a4f32e9fa'
down_revision = 'c48ba4da9e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.alter_column('imagem_blob',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)

    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produtos_ids', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('ofertas_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('produto_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produto_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('ofertas_ibfk_1'), 'produtos', ['produto_id'], ['id'])
        batch_op.drop_column('produtos_ids')

    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.alter_column('imagem_blob',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
