"""adicionao a tabela banner e ligando a tabela 

Revision ID: c48ba4da9e02
Revises: 2852fb0d5d7f
Create Date: 2025-06-16 01:47:40.810409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c48ba4da9e02'
down_revision = '2852fb0d5d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_blob', sa.LargeBinary(length=4294967295), nullable=True))
        batch_op.drop_column('imagem_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_url', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('imagem_blob')

    # ### end Alembic commands ###
